name: Faction
version: '${version}'
main: org.degree.factions.Factions
api-version: '1.21'
folia-supported: true
softdepend: ["PlaceholderAPI"]
commands:
  faction:
    description: Main command for faction management.
    usage: /faction
    permission-message: You do not have permission to use this command.
  fchat:
    description: Faction chat command.
    usage: /<command> <message>
  factionrolesync:
    description: Controls Discord faction role synchronization.
    usage: /<command> <enable|disable|status> <player>
    permission: faction.rolesync
    permission-message: You do not have permission to use this command.

permissions:
  faction.usage:
    description: Allows use of all /faction commands
    default: op

  faction.create:
    description: Allows creating factions
    default: op

  faction.stats:
    description: Allows open faction stats
    default: op

  faction.invite:
    description: Allows inviting players to a faction
    default: op

  faction.accept:
    description: Allows accepting faction invitations
    default: op

  faction.leave:
    description: Allows leaving a faction
    default: op

  faction.transfer:
    description: Allows transferring faction leadership
    default: op

  faction.rename:
    description: Allows renaming factions (admin)
    default: op

  faction.color:
    description: Allows changing faction color (admin)
    default: op

  faction.update:
    description: Update faction stats in web(admin)
    default: op

  faction.rolesync:
    description: Controls Discord faction role synchronization
    default: op
